# base image from given String
ARG BASE_IMAGE
FROM $BASE_IMAGE

# ignore complaints
ENV DEBIAN_FRONTEND noninteractive
ENV FLASK_APP=/backend/container_server.py

# install python3 and flask inside
RUN apt-get update
RUN	apt-get install -y --no-install-recommends apt-utils
RUN	apt-get -y install python3
RUN	apt-get -y install net-tools
RUN	apt-get -y install python3-pip
RUN	pip3 install requests
RUN	pip3 install Flask

# add microserver inside:
RUN mkdir /backend
RUN mkdir /backend/common
RUN mkdir /test
ADD ./felucca/backend/container_server.py /backend
ADD ./felucca/backend/common/status.py /backend/common