# base pharos image
FROM seipharos/pharos:latest

# ignore complaints
ENV DEBIAN_FRONTEND noninteractive
ENV FLASK_APP=/backend/container_server.py

# install python3 and flask inside
RUN apt-get update &&\
	apt-get install -y --no-install-recommends apt-utils &&\
	apt-get -y install python3 &&\
	apt-get -y install net-tools &&\
	apt-get -y install python3-pip &&\
	pip3 install requests &&\
	pip3 install Flask

# add microserver inside:
RUN mkdir /backend
RUN mkdir /test
ADD ../../felucca/backend/container_server.py /backend
ADD ../../felucca/backend/common /backend
ADD ../../tests/sample_output/oo.exe /test