---
- hosts: all
  become: yes  # This means that all tasks will be executed with sudo
  vars:
    venv_path: /tmp/Felucca/env/venv
    requirements_path: env/requirements.txt
  roles:
    - role: python
    - role: mongodb
    - role: angularjs
  tasks:
    - name: install docker
      become: yes
      script: ./install_docker.sh
    - name: start mongod
      become: yes
      script: ./mongodb.sh
