---
- hosts: localhost
  connection: local
  become: yes  # This means that all tasks will be executed with sudo
  vars:
    venv_path: /tmp/Felucca/env/venv
    requirements_path: "{{playbook_dir}}/requirements.txt"
  roles:
    - role: python
    - role: mongodb
    - role: angularjs
  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: install docker
      become: yes
      script: ./install_docker.sh
    - name: start mongod
      become: yes
      script: ./mongodb.sh
